backend:
  name: git-gateway
  # name: test-repo
  branch: main
  use_large_media_transforms_in_media_library: true

local_backend: true
media_folder: static/images/uploads
public_folder: ../../static/images/uploads
publish_mode: editorial_workflow

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/blog'
    create: true
    slug: '{{title}}'
    editor:
      preview: true
    locale: 'pt'
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Thumbnail', name: 'featuredImage', widget: 'image' }
      - { label: 'Data de Publicação', name: 'date', widget: 'datetime', date_format: 'DD/MM/YYYY', time_format: 'HH:mm' }
      - { label: 'Descrição', name: 'description', widget: 'string', required: false }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Texto', name: 'body', widget: 'markdown' }
      - { label: 'Áudio', name: 'audio', widget: 'string', pattern: ['[-a-zA-Z0-9@:%_\+.~#?&//=]{2,256}\.[a-z]{2,4}\b(\/[-a-zA-Z0-9@:%_\+.~#?&//=]*)?', "Link para o arquivo de áudio descrição do texto"] }
