backend:
  name: git-gateway
  use_large_media_transforms_in_media_library: true

media_folder: static/images/uploads
public_folder: ''
publish_mode: editorial_workflow
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    locale: 'pt'
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Thumbnail', name: 'featuredImage', widget: 'image' }
      - { label: 'Data de Publicação', name: 'date', widget: 'datetime', date_format: 'DD/MM/YYYY', time_format: 'HH:mm' }
      - { label: 'Descrição', name: 'description', widget: 'string', required: false }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Texto', name: 'body', widget: 'markdown' }
